import { Helper } from "../Helper";
import { views } from "../types/strategy/views";
import { ChipsCardConfig } from "../types/lovelace-mushroom/cards/chips-card";
import { StackCardConfig } from "../types/homeassistant/lovelace/cards/types";
import { TemplateCardConfig } from "../types/lovelace-mushroom/cards/template-card-config";
import { RefreshChip } from "../chips/RefreshChip";
import { AggregateChip } from "../chips/AggregateChip";

import { AbstractView } from "./AbstractView";

/**
 * Configuration for StandardDomainView
 */
export interface StandardDomainViewConfig {
  /** Domain to create view for (e.g., "light", "climate", "cover") */
  domain: string;
  /** Icon for the view (e.g., "mdi:lightbulb-group") */
  icon: string;
  /** Optional custom view configuration */
  viewOptions?: views.ViewConfig;
}

// noinspection JSUnusedGlobalSymbols Class is dynamically imported.
/**
 * Standard Domain View Class.
 *
 * Generic view class for standard domains (light, climate, cover, fan, switch, etc.).
 * Replaces 14 nearly-identical domain-specific view classes with a single configurable class.
 *
 * This class provides:
 * - Automatic badge creation with AggregateChip (global scope control)
 * - Automatic refresh chip
 * - Automatic section cards via AbstractView.createSectionCards()
 *
 * @class StandardDomainView
 * @extends AbstractView
 */
class StandardDomainView extends AbstractView {
  /**
   * Domain of the view's entities.
   */
  private readonly domain: string;

  /**
   * Default configuration of the view.
   */
  #defaultConfig: views.ViewConfig;

  /**
   * Class constructor.
   *
   * @param {StandardDomainViewConfig} config Configuration for the view
   */
  constructor(config: StandardDomainViewConfig) {
    super(config.domain);

    this.domain = config.domain;

    this.#defaultConfig = {
      icon: config.icon,
      subview: false,
    };

    this.config = Object.assign(this.config, this.#defaultConfig, config.viewOptions);

    // Empty viewControllerCard - global chips moved to badges
    this.viewControllerCard = [];
  }

  /**
   * Create the badges zone for this view.
   * Currently implemented with Mushroom Chips Cards (custom:mushroom-chips-card) as temporary solution
   * until Home Assistant native badges support templates.
   *
   * @return {Promise<(StackCardConfig | TemplateCardConfig | ChipsCardConfig)[]>}
   * @override
   */
  override async createSectionBadges(): Promise<(StackCardConfig | TemplateCardConfig | ChipsCardConfig)[]> {
    const badges: (StackCardConfig | TemplateCardConfig | ChipsCardConfig)[] = [];

    // Create aggregate chip for global domain control
    // AggregateChip automatically detects the correct configuration based on domain
    const aggregateChip = new AggregateChip({
      domain: this.domain,
      scope: "global",
      // Translation key is auto-generated by AggregateChip if not provided
      scopeName: Helper.localize(`component.linus_dashboard.entity.text.aggregate_popup.state.title_${this.domain}`),
      show_content: true,
    });

    if (aggregateChip.getChip()) {
      badges.push({
        type: "custom:mushroom-chips-card",
        chips: [aggregateChip.getChip()],
        alignment: "center",
      });
    }

    // Refresh chip (centered)
    const refreshChip = new RefreshChip();
    badges.push({
      type: "custom:mushroom-chips-card",
      alignment: "center",
      chips: [refreshChip.getChip()],
    });

    return badges;
  }
}

export { StandardDomainView };
