# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

demo:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.linus_dashboard: debug
    # homeassistant.helpers.translation: debug
