# Configuration manuelle au lieu de default_config pour éviter go2rtc
# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# Composants essentiels (remplace default_config sans go2rtc)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Intégrations de base - compatibles avec Home Assistant 2025.9.1
frontend:
config:
http:
conversation:
history:
logbook:
sun:
system_health:
mobile_app:
person:
zone:
energy:
analytics:
application_credentials:
backup:
blueprint:
counter:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
media_source:
my:
network:
schedule:
ssdp:
tag:
timer:
zeroconf:

# Configuration démo désactivée pour éviter les erreurs d'image_processing
# demo:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.linus_dashboard: debug
    # Réduire les erreurs de image_processing
    homeassistant.components.image_processing: warning
    # homeassistant.helpers.translation: debug

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    unique_id: a_very_unique_id
    code: '1234'
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    arming_states:
      - armed_away
      - armed_home
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

media_player:
  - platform: media_player_template
    media_players:
      receiver:
        friendly_name: Receiver
        unique_id: receiver
        # device_class: receiver
        # current_source_template: "{{ states('input_text.selected_source') }}"
        value_template: >
          {% if is_state("switch.decorative_lights", "on") -%}
            playing
          {%- else -%}
            off
          {%- endif %}
        turn_on:
          service: switch.turn_on
          data_template:
            entity_id: switch.decorative_lights
        turn_off:
          service: switch.turn_off
          data_template:
            entity_id: switch.decorative_lights
